services:

  # MS-APIGATEWAY
  apigateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: ms-apigateway
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      equipmed_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - equipmed_network

  # MS-EQUIPAMENTOS
  ms-equipamentos:
    build:
      context: .
      dockerfile: ./ms-equipamentos/Dockerfile
    container_name: ms-equipamentos
    ports:
      - "8081:8081"
      - "5006:5005"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      equipmed_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - equipmed_network

  # MS-OPERACIONAL
  ms-operacional:
    build:
      context: .
      dockerfile: ./ms-operacional/Dockerfile
    container_name: ms-operacional
    ports:
      - "8082:8082"
      - "5007:5005"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      equipmed_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - equipmed_network

  # REDIS OPERACIONAL
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - equipmed_network

  # MS-TRANSPARENCIA
  ms-transparencia:
    build:
      context: .
      dockerfile: ./ms-transparencia/Dockerfile
    container_name: ms-transparencia
    ports:
      - "8083:8083"
      - "5008:5005"
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      equipmed_db:
        condition: service_healthy
    restart: on-failure
    networks:
      - equipmed_network

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - equipmed_network

  # POSTGRESQL DATABASE
  equipmed_db:
    image: postgres:16-alpine
    container_name: equipmed_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data/auth:/var/lib/postgresql/data
      - ./data/postgres-init/:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d equipamentos_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - equipmed_network

networks:
  equipmed_network:
    driver: bridge