server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Rota para o ms-equipamentos
        - id: rota-equipamentos
          uri: http://localhost:8081
          predicates:
            - Path=/api/equipamentos/**

        # Rota para o ms-operacional
        - id: rota-operacional
          uri: http://localhost:8082
          predicates:
            - Path=/api/operacional/**

        # Rota para o ms-transparencia
        - id: rota-transparencia
          uri: http://localhost:8083
          predicates:
            - Path=/api/transparencia/**

# Opcional: Habilitar logs para debug de roteamento
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG