server:
  port: 8082

spring:
  application:
    name: ms-operacional

  data:
    redis:
      host: redis-operacional
      port: 6379

  datasource:
    url: jdbc:postgresql://equipmed_db:5432/operacional_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

ms:
  equipamentos:
    url: "http://ms-equipamentos:8081/api/equipamentos"