server:
  port: 8083

spring:
  application:
    name: ms-transparencia

  datasource:
    url: jdbc:postgresql://equipmed_db:5432/transparencia_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  services:
    ms-equipamentos:
      url: http://ms-equipamentos:8081/api/equipamentos
    ms-operacional:
      url: http://ms-operacional:8082/api/operacional